---
- src: git@bitbucket.org:axm-suzuki/motd-role.git
  scm: git
  version: master

- src: git@bitbucket.org:axm-suzuki/selinux-role.git
  scm: git
  version: master

- src: git@bitbucket.org:axm-suzuki/bash-completion-role.git
  scm: git
  version: master

- src: git@bitbucket.org:axm-suzuki/nginx-role.git
  scm: git
  version: master

- src: git@bitbucket.org:axm-suzuki/php-fpm-role.git
  scm: git
  version: master
